### ISSUE TITLE
Start script recursion

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/mobile#106]
**Describe the bug**
`npm run start:ios` seems to cause flickering. My Mac crashed!

![131ff2eb-5ee9-4c67-b0aa-5b35590e5fdb](https://user-images.githubusercontent.com/1184274/92750991-7fdff000-f37f-11ea-884f-649fde98ec8e.gif)

**Fix**

The script is wrong. I missed this when I reviewed @saihaj's PR and am realising now.

the start script calls itself. it should call `emulator`

**Comment by saihaj** [comment]
When I had `dev` script that was working fine. I just renamed when it was suggested in #103  and didn't check it : )
