### ISSUE TITLE
Enable Hermes on Android

### ISSUE THREAD

**Issue by Harjot1Singh** [shabados/mobile#108]
https://reactnative.dev/docs/hermes

is a open-source opt-in engine for faster JS execution on Android.

**Comment by Harjot1Singh** [comment]
@saihaj please throw in and confirm Hermes is actually working

**Comment by saihaj** [comment]
Need to enable it.
https://github.com/ShabadOS/mobile/blob/17890577c724894f95b0b6454ccbdc41c606ec44/android/app/build.gradle#L81-L84

**Comment by saihaj** [comment]
While at this do you think I should enable these too?
https://github.com/ShabadOS/mobile/blob/17890577c724894f95b0b6454ccbdc41c606ec44/android/app/build.gradle#L88-L101

**Comment by Harjot1Singh** [comment]
You can, but do check if there’s any problems with any of these before doing it

**Comment by AkalUstat** [comment]
This is also soon to be opt in for ios too https://github.com/facebook/react-native/pull/29914
