### ISSUE TITLE
Safe Area layout component  

### ISSUE THREAD

**Issue by saihaj** [shabados/mobile#112]
Should the Layout Component use [`<SafeAreaView>`](https://reactnavigation.org/docs/handling-safe-area/) under the hood instead of [`<View>`](https://reactnative.dev/docs/view)?
_Originally posted in [Slack](https://shabados.slack.com/archives/CD41G8413/p1600273582403700)_

**Comment by Harjot1Singh** [comment]
Solved in codebase
