### ISSUE TITLE
Requiring default props specified as ES6

### ISSUE THREAD

**Issue by saihaj** [shabados/mobile#113]
**Is your feature request related to a problem? Please describe.**
React is deprecating defaultProps on functional components and suggests to use ES6 default values (https://github.com/facebook/react/pull/16210). 

In order to stay future proof we will be disabling eslint rule for default props and continue with default values. But eslint can't throw error if we haven't specified a default value (where needed) and that depends when `eslint-plugin-react` resolves https://github.com/yannickcr/eslint-plugin-react/issues/2396 

**Describe the solution you'd like**
Update eslint config once that feature is released.

**Additional context**
https://twitter.com/dan_abramov/status/1133878326358171650?s=20

Checkout discussion on [Slack](https://shabados.slack.com/archives/CD41G8413/p1600301191421000)

**Comment by Harjot1Singh** [comment]
Done
