### ISSUE TITLE
Implement read-only bookmarks

### ISSUE THREAD

**Issue by Harjot1Singh** [shabados/mobile#124]
These are bookmarks that are preexisting in the database.

Parent issue #22.

### Acceptance Criteria
- Component takes a list of bookmarks to render as input
- Screen appears from bottom or side, not as modal
- Should support rendering a list of "folders"
- Clicking on an item fires a callback with what was clicked on
- Tests

### Bonus
- Virtualisation using flatlists or similar for items

@bhajneet's todo:
- Share relevant mocks
- Create `collections.json` which is a list of all folders containing bani ids:
  - `[ { name: 'Nitnem', bookmarks: [ 1, 2, 3, 4 ] } ]`

**Comment by bhajneet** [comment]
![image](https://user-images.githubusercontent.com/14130567/103214728-3fc95c80-48df-11eb-92d1-43244aff7858.png)

**Comment by bhajneet** [comment]
@Harjot1Singh we don't have bani IDs. It would be useful as different gutkae have different names for these banis. For ease of use we should use the names the users are already used to based on their school of thought. So I would have preferred:

```
{
  "1": [
    {
      "collection": "ਨਿਤਨੇਮ",
      "bookmarkIds": {
        "JJS": {
          "name": "ਜਪੁ ਜੀ ਸਾਹਿਬ",
          "lines": [
            {
              "header": "ਜਪੁ ਜੀ ਸਾਹਿਬ"
            },
            {
              "start_line": "0NVY",
              "end_line": "9WAL"
            }
          ]
        },
        "JAS": {
          "name": "ਜਾਪੁ ਸਾਹਿਬ"
        },
        "TPS": {
          "name": "ਤ੍ਵ ਪ੍ਰਸਾਦਿ ਸਵਯੇ (ਸ੍ਰਾਵਗ ਸੁਧ)",
          "name": "ਤ੍ਵ ਪ੍ਰਸਾਦਿ ਸਵਯੇ",
          "name": "ਤ੍ਵਪ੍ਰਸਾਦਿ ਸਵਯੇ"
        }
      }
    }
  ],
}
```

Note you can create your own bookmarks this way, we are not reliant on database which is the base for multiple projects. We can also add headers and such in our custom json. It would also be nice to be able to name the same bani different ways based on school of thought. Idea: we can also use unicode names and transliterate to the localization language.

Given no Bani IDs, I've done it using [banis.json](https://github.com/shabados/database/blob/dev/data/banis.json)'s "name_english" field for now:

```
{
  "1": [
    {
      "name": "Nitnem",
      "name_english": [
        "Jap Ji Sahib",
        "Jaap Sahib",
        "Tav Prasad Savaiye (Sravag Sudh)",
        "Benti Chaupai Sahib",
        "Anand Sahib",
        "Rehras Sahib",
        "Ardaas",
        "Sohila Sahib"
      ]
    }
  ],
  "2": [
    {
      "name": "Sundar Gutka",
      "name_english": [
        "Jap Ji Sahib",
        "Jaap Sahib",
        "Tav Prasad Savaiye (Sravag Sudh)",
        "Benti Chaupai Sahib",
        "Anand Sahib",
        "Shabad Hazare",
        "Barah Maha",
        "Shabad Hazare Patshahi 10",
        "Tav Prasad Savaiye (Deenan Ki)",
        "Rehras Sahib",
        "Ardaas",
        "Aarti",
        "Sohila Sahib",
        "Bavan Akhri",
        "Sukhmani Sahib",
        "Asa Ki Var",
        "Oankaar",
        "Sidh Gosht",
        "Lavan (Anand Karaj)",
        "Chandi Di Var",
        "Sri Guru Granth Sahib Paath Bhog (Ragmala)"
      ]
    }
  ]
}
```

This collections.json is missing a few from sundar gutka which are available in our database, but not populated in our db's banis.json file. I think being able to add these as custom in mobile repo would be easier than adding them to the database project.

**Comment by Harjot1Singh** [comment]
@bhajneet We definitely do have bani IDs, but currently, they're just in the order of the JSON file e.g. Japji Sahib = 1 etc. v5 will move to immutable Bani IDs.

**Comment by AkalUstat** [comment]
quick question: is the list data (shabads AND banis) just going to be ids or more like what @bhajneet is suggesting

**Comment by Harjot1Singh** [comment]
Design what seems most sensible as an input and just assume we can hook in the data however we'd like after. You don;t have to deal with data fetching yourself etc, so you can assume the latter
