### ISSUE TITLE
Add CodePush support

### ISSUE THREAD

**Issue by swissarmykirpan** [shabados/mobile#13]
Enable App Center codepush so that we can release updates to the app without having to go through a formal appstore release process (which can take days).

### AC2
**Given** a registered user with the app downloaded
**When** an non-native update is pushed out
**And** the registered user opens the app
**Then** the user instantly has the latest update (via codepush)

Blocker: we need to check whether we'd like to go with expo-updates or app center codepush!

**Comment by saihaj** [comment]
https://github.com/Microsoft/react-native-code-push

**Comment by manjotsk** [comment]
**Spike**: Going to implement this. I will also consider hosting the bundles on a self-hosted remote server or bucket!
Goals: 
1. Impact analysis regarding any change in development workflow, which includes the introduction of additional native libraries.
2. Identify possible limitations that might impact the app behaviours and DX in the long and the short run!

**Comment by Harjot1Singh** [comment]
Since moving to expo, this is no longer a requirement. We'll likely use EAS
