### ISSUE TITLE
Investigate feature flagging services

### ISSUE THREAD

**Issue by Harjot1Singh** [shabados/mobile#138]
## Investigation

Look into feature flagging services that we can use. This is crucial for building features. We are looking for something that has:

- An OSS friendly plan (free or heavily discounted)
- Feature flags
- Feature flag variables
- A/B testing (or experiments)
- Optionally, scheduled feature flags. Not really sure on how many services offer this, but this would be great
- Audiences

We also need to know how offline-friendly the FF service is:
- Does it pull down the state of the feature flags on app load? => better connectivity
- Does it cache the state between app loads? => offline support

## Timebox
2 days

## Outcome

- Table/List of potential services with
  - Name
  - URL
  - Cost to us
  - Additional Features beyond the above list
  - Missing feature of the above list
  - Brief answers to offline-friendly questions above
- Recommendation for which service to use
- A new ticket to register for and implement the feature flagging provider/populate rest of epic

**Comment by saihaj** [comment]
<figure class="md-table-fig" cid="n0" mdtype="table" style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(201, 209, 217); color: rgb(201, 209, 217); font-family: Nunito, sans-serif; font-size: 18px; text-align: justify; background-color: rgb(13, 17, 23);">

Name | Url | Cost | Feature flags | A/B testing/experimenting | Audiences | Scheduled | Others
-- | -- | -- | -- | -- | -- | -- | --
LaunchDarkly | https://launchdarkly.com | Contact for OSS discount eligibilty | yes | Yes | Yes | Yes | Analytics
Cloudbee | https://www.cloudbees.com/products/feature-management | Contact for OSS discount eligibilty | Yes | Yes | Yes | Yes | Config as code, Analytics
Split | https://www.split.io/product/feature-flags/ | Generous Free plan | Yes | Yes | Yes | No | Analytics, Alerts
ConfigCat | https://configcat.com | Generous Free plan | Yes | Yes | Yes | No |  
AB Tasty | https://www.abtasty.com/feature-flagging/ | Need to contact and see website doesn't tell | Yes | Yes | Yes | No | Personalization

</figure>

**Comment by Harjot1Singh** [comment]
Great! Please also look into unleash.io

**Comment by Harjot1Singh** [comment]
And also harness.io

**Comment by Harjot1Singh** [comment]
**Outcome**
Going with Split! There is a way of doing timed releases: https://help.split.io/hc/en-us/articles/360053285391-How-to-do-a-timed-release-of-a-feature-toggle-Split-On-Treatment-.

We should test this works as expected.

If Split is not sufficient, we'll look at Unleash as the next priority.
