### ISSUE TITLE
Move to main branch

### ISSUE THREAD

**Issue by Harjot1Singh** [shabados/mobile#152]
Currently, we have a `master` and `dev` branch. We should move to a `main` branch in order to build sensible pipelines and not cause confusion.

This should only be done when there are no other active pull requests open, and `dev` should be renamed to `main`, with `master` deleted.

**Comment by bhajneet** [comment]
```
git branch -m dev main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
