### ISSUE TITLE
Add right settings pane

### ISSUE THREAD

**Issue by Harjot1Singh** [shabados/mobile#172]
# User Persona, Goal, and Motivation

As any user, I want to open the settings pane, so that I can view future toggles to customise my Shabad OS experience.

# Acceptance Criteria

**AC1**
* GIVEN a user is on the Gurbani view
* WHEN user swipes left
  * OR the user taps the settings icon in the navbar
* THEN an empty settings view is shown

# Approach

Use React Navigation primitives to create this. See #131 - can recreate if needed.

# Mockup

![image](https://user-images.githubusercontent.com/14130567/143776512-35f5fcb3-af92-438b-9dab-fe80b4b10db8.png)

**Comment by bhajneet** [comment]
I think this will help:

https://github.com/satya164/react-native-tab-view

```
<TabView
  renderTabBar={() => null}
  ...
/>
```

That's what React Navigation uses anyways: https://reactnavigation.org/docs/material-top-tab-navigator/

**Comment by Harjot1Singh** [comment]
## Testing

❌ Navigation primitive should be Instagram-like - shared edge if possible, and swipe on main screen left to trigger it.

**Comment by Harjot1Singh** [comment]
Testing passed
