### ISSUE TITLE
Top bar and bg of main content and modal windows should be different

### ISSUE THREAD

**Issue by bhajneet** [shabados/mobile#184]
# Acceptance Criteria

## AC1

* GIVEN app is in a fresh/clean state
* WHEN user views main content or side panes (Timeline and Settings)
* THEN top bar and background should match main view / side pane mockup

## AC2

* WHEN user opens/views a modal screen
* THEN top bar and background should match modal mockup

# Approach

Top bar and background color of main content view is not supposed to be gray, it should be decoupled from modal top bar

- [x] #253
- [x] #254

Note: the app does not have to react to dark/light mode changes during the running of the app - this will be handled in a separate ticket.

# Mockup

top two are from main area (no modals) and bottom two are in search modal

![image](https://user-images.githubusercontent.com/14130567/145687424-9242c783-ada3-4ce5-87b6-6ea04fa8eaba.png)

**Comment by Harjot1Singh** [comment]
Moved back into refinement as it needs revisiting - react navigation has its own defaults that we may want to use!
