### ISSUE TITLE
Change title of Collections modal as you browse

### ISSUE THREAD

**Issue by bhajneet** [shabados/mobile#185]
# Acceptance Criteria

## AC1

* GIVEN user is viewing clean/fresh collections modal
* WHEN user taps into a collection (e.g. nitnem / sundar gutka)
* THEN title of modal should change to name of collection (e.g. nitnem / sundar gutka)

## AC2

* Given titles of collections modal changes
* When user is going into a collection or going back to the list of collections
* Title change should be animated. For now it can be a cross fade, but it would be even better to indicate direction by moving the old text in the away direction and the new text from the coming direction.

# Approach

- [ ] 

# Mockup

**Comment by Harjot1Singh** [comment]
Done
