### ISSUE TITLE
Be able to drag down a modal from vertical gesture in middle of the screen

### ISSUE THREAD

**Issue by bhajneet** [shabados/mobile#187]
# User Persona, Goal, and Motivation

I am an iOS user, I want to pull down a modal that is already at the top of it's view, so that I can use the app the same as other apps like Apple News/Podcasts/Music/Safari, Instagram, and Signal.

# Acceptance Criteria

## AC1

* GIVEN modal is in a fresh/new state with user already scrolled at the top of the content
* WHEN user gestures top to bottom in the modal content area
* THEN animate close the modal

## AC2

* given modal is in a dirty/scrolled state
* when user gestures top to bottom in the modal content area
* then scroll content as you normally would

## AC3

* given modal is being scrolled to the top and hits the top edge and bounces
* when user tries to gesture top to bottom while modal content is still bouncing from it's last scroll
* then keep pulling content downwards, do not animate slide close modal

# Approach

See https://stackoverflow.com/a/51572650 - adding `vertical` instead with the height of the modal should work for us.

# Mockup

**Comment by manjotsk** [comment]
@bhajneet @Harjot1Singh  Can you elaborate more on that? Let's use wireframe?

**Comment by bhajneet** [comment]
@Harjot1Singh I think some help on the approach is being requested, in case you haven't seen this already

**Comment by Harjot1Singh** [comment]
This ended up being fixed as part of switching to native stack navigators, which support this OOTB!
