### ISSUE TITLE
Finish mocking up android

### ISSUE THREAD

**Issue by bhajneet** [shabados/mobile#20]
The iOS version is complete enough. Need to finish Android and then make sure workflows/ui/ux is relatively consistent and doable across both.

**Comment by saihaj** [comment]
Cross platform has been working fine so far example is Shortcuts Drawer #57. Is this issue even needed? Pinging @Harjot1Singh

**Comment by bhajneet** [comment]
Yes it's fine for both platforms in our new mockup
