### ISSUE TITLE
Implement bookmarks

### ISSUE THREAD

**Issue by bhajneet** [shabados/mobile#22]
Bookmarks should act on the current tab, bookmarks should include:

- Folders (events, gurpurabs, themes, etc.)
- Dynamic bookmarks
- Regular shabad/dictionary bookmarks (user definable)
- Compilations / banis (e.g. nitnem, asa ki vaar)

Mockup example:
![image](https://user-images.githubusercontent.com/14130567/78699235-93b78f80-78d1-11ea-9ac7-6dec81f48c7a.png)

**Comment by bhajneet** [comment]
Bookmarks that come preloaded can be hidden but not permanently deleted. Users can also add their own bookmarks to preloaded folders, which could be deleted by them.

In future, if we push an update to modify the preloaded bookmarks/folders, it should gracefully manage the changes users have made.

**Comment by bhajneet** [comment]
Note: Change Asa ki Vaar to a single compiled bookmark, not a folder as shown in the picture.

**Comment by Sarabveer** [comment]
`ਇਤਿਹਾਸਕ ਦਿਹਾੜੇ`

**Comment by Sarabveer** [comment]
Maybe ਸੰਸਕਾਰ is a better term for Ceremonies, it is what Sikh Rehat Maryada uses.

**Comment by bhajansweet** [comment]
> Maybe ਸੰਸਕਾਰ is a better term for Ceremonies, it is what Sikh Rehat Maryada uses.

It also says "reetiyan" in the text. I think whatever is more commonly understood is fine.

**Comment by bhajansweet** [comment]
When creating bookmarks, user should be given a default title but should be allowed to rename it. 

Bookmarks should be created from either the quickdrawer or after long-pressing on a tuk.

If done from the quickdrawer, it will save based on the current view:
 - When reading an Ang, it would save as a dynamic bookmark with default bookmark title like "Sri Guru Granth Sahib Paath MMDDYY"
 - When reading a Shabad, would save as a standard bookmark with default title set to title of tab

If created from long-press, it should always (regardless of ang-view or shabad-view) save as standard bookmark with default title set to that tuk.

**Comment by bhajansweet** [comment]
UI for creating bookmarks should be similar to how YouTube adds videos to lists.

Also, should be able to long-press on a bookmark to rename it.

When in a bookmark (as in, you clicked on the bookmark from the bookmarks modal, NOT after creating a bookmark from a search result), updating the "main line" should notify user of updated bookmark (and include edit button to rename or further modify the updated bookmark).

**Comment by AkalUstat** [comment]
ok so if i understand this correctly, then bookmarks thing is just a modal, or is it a separate page (or both)?

**Comment by bhajneet** [comment]
Modal in the sense it can be pulled down to reveal the tab you were on before you hit bookmarks icon.

Page in the sense that you can navigate to different parts of the folder structure in bookmarks.

**Comment by bhajneet** [comment]
Should be similar to YouTube in the sense that we are adding bookmarks to potentially multiple lists / folders

There should be no bookmarks in root folder. And perhaps we should restrict to only one level of folder.

So root level has a bunch of folders / lists to which a user can add bookmarks to. No second level folder.

**Comment by bhajneet** [comment]
List vs Folder discussion https://github.com/ShabadOS/desktop/issues/483
