### ISSUE TITLE
Duo investigate usage of fonts on RN / Android

### ISSUE THREAD

**Issue by bhajneet** [shabados/mobile#224]
# Issue

There are some unicode gurmukhi characters that Android's system font cannot display properly.

# Investigation

As far as @bhajneet knows, React Native doesn't allow fallback fonts. If you specify a font and the character doesn't exist, it will not be rendered (it will not fallback to the system font). The system font for Android does really well, except for many subjoined characters in Gurmukhi. It cannot render ਨ੍ਤ ਨ੍ਚ ਨ੍ਟ the way it renders ਨ੍ਰ. This issue does not exist on iOS, which uses Mukta Mahee, a font that can render the subjoined characters.

So we cannot define Mukta Mahee as the base font for Android, because eventually we will want to display something outside of Latin / Gurmukhi characters. And if you specify a font in React Native, and it doesn't exist, there is no fallback. So we wouldn't be able to render those characters without adding more fonts and customizing where those fonts are being shown.

Personally I would prefer to use the system font where ever possible, and specify specifically when we anticipate special characters. So that only applies to a small subset of characters for gurmukhi on Android.

Things checked:

- It is not possible to define more than one font family on RN (no fallbacks).
- It is not possible to define a font for a specific unicode range.
- Defining a font on Android limits it to only two font weights: 400 (regular) and 700 (bold). But you can style using any number of fonts, so you can have different fonts for different style classes/definitions, but you cannot have more than one font (no fallbacks).
- https://stackoverflow.com/questions/38815234/how-to-add-fonts-for-different-font-weights-for-react-native-android-project This might solve the issue for multiple font weights

# Timebox

- 0.5 days

# Outcome

- Solution for how we will handle special characters like ਨ੍ਤ ਨ੍ਚ ਨ੍ਟ with the most minimal use of custom fonts.
- A ticket to consolidate every usage of `Fonts.MuktaMahee` and split Units Enum

**Comment by Harjot1Singh** [comment]
Thanks for filling this out! I think it could benefit with some context/introduction on what we're trying to achieve/solve & why.

**Comment by bhajneet** [comment]
After investigation a custom font must be used on iOS and Android for gurbani for specific character combos. It is possible to use ASCII as already being done for Presenter or to create a custom unicode font based on the existing open source mukta mahee.
