### ISSUE TITLE
Add reader mode

### ISSUE THREAD

**Issue by bhajneet** [shabados/mobile#24]
# User Persona, Goal, and Motivation

I am a traditional reader, I want to view gurbani like I would in a gutka, so that I can do paath comfortably  (less scrolling and visually more natural).

# Acceptance Criteria

## AC1

- **Given** a user is on the settings screen
- **When** they toggle the reader mode element
- **Then** the reader mode is toggled on/off

## AC2

- **GIVEN** shabad is shown
- **WHEN** reader mode is toggled
- **THEN** show only shabad script in paragraphs of pauris (no translations and transliterations)
- **And** the font is larger

## AC3

- **GIVEN** reader mode is toggled
- **WHEN** displaying manglacharan / header lines
- **THEN** show them as individual lines in a larger font, center-aligned (see mock)

AC3 may be revisited as a future ticket, as we may not have the data available. @bhajneet to move into a new ticket.

# Approach

- [x] #235
- [x] #236

# Mockup

![image](https://user-images.githubusercontent.com/14130567/139515018-73c0d4ca-0656-414f-b178-c5988a7a3a22.png)

# Old

Have an option to quickly switch the view to "reader mode" which may group pauris together in paragraphs, may also hide all translations, may switch to larrivaar, etc. based on whatever the user has dictated in "reader mode settings".

Could then add new issues for setting bookmarks to open in specific reader mode on a case by case or overall "type of bookmark" method.

**Comment by bhajneet** [comment]
Toggle for switching in and out of reader mode would be hidden in drawer.

**Comment by saihaj** [comment]
Need a mockup for this required by #74

**Comment by bhajneet** [comment]
2 comments (one of which I think is easily resolvable):

- No space between lines merged together
- No title of bookmark at the top

**Comment by bhajneet** [comment]
Also, not sure how... but I got this by toggling on and off

![image](https://user-images.githubusercontent.com/14130567/157157024-acdff22a-a509-4fa3-9b61-d1de1c085940.png)

**Comment by bhajneet** [comment]
And I have no clue how I did this one

https://user-images.githubusercontent.com/14130567/157157338-fa548bd0-5c9c-4a99-b7c5-49204ee22648.MOV

**Comment by bhajneet** [comment]
Possibly related / helpful

https://user-images.githubusercontent.com/14130567/157157521-53fd9ff5-3e52-49fe-b856-d6506040ebe7.MOV

**Comment by Harjot1Singh** [comment]
The title is not part of the ACs btw! Ok with filing another ticket under the reader mode epic for this?

**Comment by Harjot1Singh** [comment]
Do track a new ticket for retaining scroll position between the toggles in another ticket under the epic

**Comment by Harjot1Singh** [comment]
Final question - do you have a preference on how much larger? The mocks show the original font size, except for the first few lines

**Comment by bhajneet** [comment]
> Final question - do you have a preference on how much larger? The mocks show the original font size, except for the first few lines

For now let's do 25%. I created a ticket to investigate it further.

**Comment by Harjot1Singh** [comment]
Space and font have been adjusted. Will look into the bug.

**Comment by Harjot1Singh** [comment]
Please re-test!
