### ISSUE TITLE
Content jumps in steps in after-content scroll animation

### ISSUE THREAD

**Issue by bhajneet** [shabados/mobile#261]
# Describe the bug

Jittery content scroll, when going past content

# Step to reproduce behavior

## Method 1
1. Keep scrolling up slowly past end of content

## Method 2
1. Scroll to end of content.
2. Wait for scroll bounce to stop bouncing -- or -- for content to stop moving completely
3. Scroll up a little, then quickly and aggressively scroll down past the content

# Screenshots

https://user-images.githubusercontent.com/14130567/150850452-a7bd1d6d-e85a-4ad8-a6ab-a59b6c2d1aff.mp4

**Comment by bhajneet** [comment]
Still exists on `0.1.0 (28)`. Another note is that scrolling up with two fingers (scrolling all the way up, then using another finger to keep pulling up, then alternating back to original finger to keep pulling up) causes some jitters as well. This does not happen at the top of the content when pulling down with alternating fingers. I suspect it has to do with finding new lines / virtualized lists.

**Comment by Harjot1Singh** [comment]
Needs more investigation 🤔

**Comment by Harjot1Singh** [comment]
Could not reproduce in #321
