### ISSUE TITLE
Cannot scroll content when swiping on fadeaway gradient

### ISSUE THREAD

**Issue by bhajneet** [shabados/mobile#273]
# Describe the bug

There is a fadeaway gradient behind the search/bookmarks bottom bar. This gradient extends up to the content.

The user cannot scroll content if trying to pull from that gradient area.

# Expected behavior

Either lessen the gradient range or remove the gradient and differentiate the bottom bar differently.

**Comment by Harjot1Singh** [comment]
This is surprisingly annoying

**Comment by bhajneet** [comment]
I wonder if this and #274 are related. Maybe if that is fixed, this will also be pushed downwards? I'm not sure.

**Comment by bhajneet** [comment]
Re-opening to discuss. There is no gradient at all now. Not sure if that was intended. Can say it's fixed, but not sure.

**Comment by bhajneet** [comment]
Okay, I see there is a gradient. But a different background is cutting content off sharply. So there is a mistake in implementation.
