### ISSUE TITLE
Cannot gauge amount of content based on scrollbar

### ISSUE THREAD

**Issue by bhajneet** [shabados/mobile#275]
# Describe the bug

It is not possible to tell how close to the "end" of content you are with the scrollbar position. Many times it will change because more content loads as you near the end. This may confuse users who want an idea of their reading position.

**Comment by Harjot1Singh** [comment]
Let's revisit in refinement and see if we can find a good way to fix

**Comment by Harjot1Singh** [comment]
This should be much improved with the work in #321
