### ISSUE TITLE
Pressing settings and back button eventually breaks buttons on Home Screen

### ISSUE THREAD

**Issue by Harjot1Singh** [shabados/mobile#278]
# Describe the bug
As per the title, continuously pressing settings and back button eventually breaks buttons on Home Screen and settings screen...

# Step to reproduce behavior

1. On the Gurbani screen, press the settings button
2. On the settings screen, press the back button
3. Repeat the above fast until the buttons stop responding on either screen. Swiping still works but the navigation buttons do not. 

# Expected behavior

The navigation icon buttons should continue to work.

# Screenshots

# Bug environment

 - Device: iPhone X
 - OS: iOS 15
 - Browser:
 - Version:

**Comment by bhajneet** [comment]
For me, I can start swiping panes, leave the swipe quarter way done, and start spamming the back button. This will break everything including sliding.

**Comment by Harjot1Singh** [comment]
Fixed in 4ae3234c9118631a304ab04a9fc1508cc644cd7d with a workaround to extend the tab navigator and disable swipe every time navigation occurs. Very irritating bug and could not find a solution anywhere.
