### ISSUE TITLE
Mismatching colors for Separator border-line

### ISSUE THREAD

**Issue by bhajneet** [shabados/mobile#279]
# Describe the bug
Two colors being shown. I believe because of 0.5 unit height being used.

# Expected behavior
Uniform separator color

# Screenshots
![image](https://user-images.githubusercontent.com/14130567/156861006-b826605e-ff45-4aa2-8eaf-ba279bedcae0.png)

**Comment by Harjot1Singh** [comment]
This is fixed by b189aca8ddce113ebe7cb00ea436a3623d66aeff.

For heights less than 1, you need to use the hairline width constant that comes with react native.
