### ISSUE TITLE
Swap mukta mahee for indigo

### ISSUE THREAD

**Issue by bhajneet** [shabados/mobile#288]
Let's see what https://github.com/TiroTypeworks/Indigo looks like in the app.

**Comment by Harjot1Singh** [comment]
![image](https://user-images.githubusercontent.com/1184274/159144719-6591a10e-c55d-4b5c-b5e5-e8f1d1eef078.png)
This is what it looks like

**Comment by Harjot1Singh** [comment]
Should this be switched out for both iOS and Android, or just Android? And would you like to proceed after seeing this?

**Comment by bhajneet** [comment]
Picture was fine
