### ISSUE TITLE
Tried to run on android phone

### ISSUE THREAD

**Issue by harpreet9629** [shabados/mobile#306]
### Describe the bug

Satsariakaal Ji,

I tried to run debug app on android phone and i got some errors. Please check attached screenshot.
![Screenshot_1](https://user-images.githubusercontent.com/26606638/179190183-0efb429e-faba-4702-b255-cb2e294b9250.jpg)

### Environment

Android 11

**Comment by Harjot1Singh** [comment]
🙏🏽

It might be that you're missing some environment variables for local dev - maybe we didn't push them up. Will have a look soon!

**Comment by harpreet9629** [comment]
It's related to split.io package? env files are there under config folder. Have to change split.io package key?

**Comment by bhajneet** [comment]
If yours matches with https://github.com/shabados/mobile/blob/main/config/.env.local, then @Harjot1Singh please note that I'm not having issues starting with this env file.

@harpreet9629 what's your machine? Windows/macOS?

**Comment by harpreet9629** [comment]
> If yours matches with https://github.com/shabados/mobile/blob/main/config/.env.local, then @Harjot1Singh please note that I'm not having issues starting with this env file.
> 
> @harpreet9629 what's your machine? Windows/macOS?

Yes all variables are same as this file

**Comment by bhajneet** [comment]
@harpreet9629 have you made any changes to the codebase?

**Comment by harpreet9629** [comment]
@bhajneet no paji, just cloned and run npm i and then npx react-app run-android

**Comment by bhajneet** [comment]
If you don't mind, please try following the instructions in [CONTRIBUTING.md](https://github.com/shabados/mobile/blob/main/CONTRIBUTING.md), and let us know if that helps!

**Comment by harpreet9629** [comment]
Ok Sure,

Thanks

**Comment by bhajneet** [comment]
@harpreet9629 is this still an issue?

**Comment by harpreet9629** [comment]
No, there's no issue , tested in android emulator its working fine.

**Comment by bhajneet** [comment]
That's great to hear! If you'd like to pick up some work and contribute a PR to the project, please take a look at our backlog: https://github.com/orgs/shabados/projects/9/views/4

If there is something else you would like to work on (to fix, improve, add features, etc) that is not in the backlog, please let us know! Hoping we can work together on improving this project :)

**Comment by harpreet9629** [comment]
Ok Sure Paji :)
