### ISSUE TITLE
Which dependencies are required?

### ISSUE THREAD

**Issue by bhajneet** [shabados/mobile#313]
### Question

As per `npx depcheck`

Unused dependencies:
* @react-native-community/masked-view
* @react-native-community/toolbar-android
* promise

Unused devDependencies:
* @commitlint/cli
* @commitlint/config-conventional
* @prettier/plugin-ruby
* @types/jest
* @types/jest-when
* husky
* jest-transform-stub
* jest-when
* jetifier
* metro-react-native-babel-preset
* prettier

Missing dependencies:
* eslint-plugin-simple-import-sort: ./.eslintrc
* eslint-config-airbnb: ./.eslintrc
* eslint-plugin-jest: ./.eslintrc
* eslint-plugin-import: ./.eslintrc
* eslint-plugin-react: ./.eslintrc
* eslint-plugin-jsx-a11y: ./.eslintrc
* eslint-plugin-react-hooks: ./.eslintrc
* @typescript-eslint/eslint-plugin: ./.eslintrc
* eslint-config-airbnb-typescript: ./.eslintrc
* @typescript-eslint/parser: ./.eslintrc

**Comment by Harjot1Singh** [comment]
Narrowed down in #321
