### ISSUE TITLE
Add localisation option to Setting pane

### ISSUE THREAD

**Issue by saihaj** [shabados/mobile#39]
# User Persona, Goal, and Motivation

I am a non-English user, I want to see the UI in a readable language, so that I can naturally interact with Shabad OS.

# Acceptance Criteria

## AC1

* GIVEN user is on the Settings pane
* WHEN the user taps "App Language" button
* THEN the "App Language" drawer is viewable with language options
	* `pa-in (punjabi)`
    * `en-gb` (english uk)
    * `en-us` (english us) 

## AC2

* GIVEN the user is viewing the "App Language" drawer
* WHEN user taps a language option
* THEN that language gets a filled green circle
  * AND the drawer automatically closes
  * AND setting of "App Language" in Settings pane is updated with selected language

## AC3

* GIVEN "App Language" drawer is on screen
* WHEN user taps any of the following:
  * Currently selected language
  * Cancel button
  * Outside the drawer
  * Dragging down the drawer
* THEN drawer disappears without updating anything

## AC4

* GIVEN an app language is chosen
* WHEN some aspect of the UI is being shown
* THEN the localised components should be displayed in the chosen language

# Approach

- [x] #210
- [x] #211
- [x] #212

# Mockup

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/14130567/139286876-00bcdad2-fe33-49d9-b17e-da1d13e42666.png">

# Related
- Resource: https://github.com/stefalda/ReactNativeLocalization
- Base work done in #116 

# Blocked By
- #172 
- #215

**Comment by bhajneet** [comment]
Should be one of the early choices when first starting the app / initial app set up

**Comment by saihaj** [comment]
Base work was done https://github.com/shabados/mobile/pull/116. Pinging @Harjot1Singh to close this or update status.

**Comment by Harjot1Singh** [comment]
Let's create/rename the issue to relate to configuring localisation language, since we've done the base work, and it's a matter of exposing config to the user now

**Comment by Harjot1Singh** [comment]
https://github.com/shabados/mobile/issues/211#issuecomment-1073283462

Need to add proper fallback to region. E.g. if English (australia) is top of user preferences (language english, region au) and french (France) is next, the app should attempt to go for the next best english option, rather than fallback to the next direct match (french)

**Comment by Harjot1Singh** [comment]
Resolved by moving `en-US` to `en` to ensure that there is a language-level default specifier always present - works fine when this is done
