### ISSUE TITLE
Continuous Delivery

### ISSUE THREAD

**Issue by swissarmykirpan** [shabados/mobile#4]
All things to enable mobile apps being able to be released continuously.

**Comment by preetcharan** [comment]
hello

**Comment by Harjot1Singh** [comment]
Related #13 
Related #6

**Comment by Harjot1Singh** [comment]
CI in https://github.com/ShabadOS/mobile/pull/66/commits/98824bddbdebaa25eb96004850f6ee9e02ad1c4f

**Comment by saihaj** [comment]
https://github.com/r0adkll/upload-google-play

Example of this action https://github.com/r0adkll/DeckBox/tree/master/.github/workflows

**Comment by saihaj** [comment]
check out browser stack

**Comment by Harjot1Singh** [comment]
Encapsulated by #6 for our purposes now
