### ISSUE TITLE
add search filters scrolling strip

### ISSUE THREAD

**Issue by bhajneet** [shabados/mobile#43]
Example mockup below. The search filters scrolling tab is just below the input box for search. By default no filters are on.

The search is meant to be interpretive, e.g. type latin **man**, return results for:
- transliteration: _bhe puneet pavitr **man** janam janam ke dukh hare |1| rahaau |_
- translation: _Because, he created angels out of ordinary hu**man** beings,_

Or, e.g. type gurmukhi **ਨਨਕ**, return results for 
- first letters: _**ਨਿ**ਹਕੰਟਕੁ **ਨਿ**ਹਕੇਵਲੁ **ਕ**ਹੀਐ ॥_
- main letters: _**ਨਾਨਕ** ਹੁਕਮੈ ਜੇ ਬੁਝੈ ਤ ਹਉਮੈ ਕਹੈ ਨ ਕੋਇ ॥੨॥_

And we also interpret results to help users. For example if the user types nanak with extra character on last letter, then we can search the main letters, in case the full word doesn't return results, after the full word results (see in mockup top results, first letters, headers we would have main letters after full words in this example). 

So users may wish to turn on/off these extra search modes or search targets. To help refine the results, these filters are available. Users may refine by:

- Search target (i.e. Bani, Translation, Pronunciation, that's it)
- Search mode (i.e. First Letters and Main letters, that's it)
- Composition (e.g. Sri Guru Granth Sahib Ji, Dasam Granth, ...)
- Author (Guru Nanak Dev Ji, Bh Nand Laal ji, ...)

The last two are perhaps better done as filter/sort dropdowns in a pop-up/modal window a la _https://github.com/ShabadOS/mobile/issues/42_

![image](https://user-images.githubusercontent.com/14130567/79001622-c86b5700-7b1c-11ea-9261-ca7514267a77.png)

_Related to https://github.com/ShabadOS/desktop/issues/395_

**Comment by saihaj** [comment]
@bhajneet is this deprecated as per new design?
