### ISSUE TITLE
add search input switcher (keyboard / ascii to gurmukhi vs unicode)

### ISSUE THREAD

**Issue by bhajneet** [shabados/mobile#44]
This would be in addition to the normal/default keyboards of Android / iOS (which already come bundled with latin and gurmukhi keyboards). This is for users that don't know how to switch to unicode keyboards in android/iOS.

This switch would convert ascii characters to gurmukhi unicode in the search bar/input box.

Different ways to do it: 

- The button changes the keyboard of the OS (not sure if this is possible? but even if it were it doesn't help people with external keyboards I don't think)
- The button pops up a custom keyboard (benefit here is that external keyboards are still inputting ascii characters as the custom keyboard inputs ascii latin which is auto converted by search input, and we also get to lay out the characters as we think it's easiest for users). Direct translation of https://github.com/ShabadOS/desktop/issues/394

The toggle would also change the search input. If the input is already in unicode gurmukhi, do nothing. If it were in latin characters (e.g. `jkm`), then toggling on would convert these letters (e.g. `ਜਕਮ`).

This allows the search to be much more fluid/easy. If the user typed it in wrong, they could always toggle the button to convert the search without re-typing it. If the user wants to switch from gurmukhi (first letter, full word, main letters, pronunciation, etc.) to latin (translation, translit, etc.) it's an easy toggle.

Not sure yet whether this button will be in/on left side of search bar/input box or if it will be part of the filter/sort button menu (if we have a filter/sort button menu) related to https://github.com/ShabadOS/mobile/issues/42 and https://github.com/ShabadOS/mobile/issues/43

**Comment by saihaj** [comment]
@bhajneet is this deprecated as per new design? If so please close this thanks!

**Comment by bhajneet** [comment]
Unsure still
