### ISSUE TITLE
Android / iOS UI Test

### ISSUE THREAD

**Issue by bhajansweet** [shabados/mobile#49]
We'd like to make sure that there are no issues using React Native to implement the same features across both platforms. The specific functionality we'd like to test are:

* [ ] Standard Shabad View (test scrolling) (#94)
* [X] Draggable Drawer (#93)
* [ ] Search button and search modal functionality as per Figma mockup (#95)

**Comment by saihaj** [comment]
We can modify this to make the bottom navigator https://github.com/osdnk/react-native-reanimated-bottom-sheet

**Comment by saihaj** [comment]
Ordering of tabs: https://youtu.be/hh7vfMzHTIg

**Comment by Harjot1Singh** [comment]
I think this issue will be deprecated as per the new design. @bhajneet?

**Comment by Harjot1Singh** [comment]
fwiw, our tests did show that cross-platform drawer worked nicely :)

**Comment by bhajneet** [comment]
We can close this issue. I'd say it's tested well enough by now.
