### ISSUE TITLE
Investigate usage analytics

### ISSUE THREAD

**Issue by saihaj** [shabados/mobile#67]
## Investigation

Look into usage analytics services that we can use. This is crucial for understanding our users. We are looking for something that has:

- An OSS friendly plan (free or heavily discounted)
- Ability to use cross-platform 'audiences' with feature flag service
- Ability to count overall time spent, time spent scrolling on certain screen, clicks/taps of buttons/menus
- GDPR / Privacy laws integration

## Timebox
2 days

## Outcome

- Table/List of potential services with
  - Name
  - URL
  - Cost to us
  - Additional Features beyond the above list
  - Missing feature of the above list
- Recommendation for which service to use
- A new ticket to register for and implement the usage analytics/populate rest of epic

**Comment by bhajneet** [comment]
I had never thought of using shake device as a command. I'm curious if we could use that for something else which might get more use. Cool idea!

**Comment by saihaj** [comment]
For our testing versions we can use something like this https://github.com/marketplace/instabug

For production we can check out https://count.ly/ as it has all the things we need and will also help with Desktop.

**Comment by bhajneet** [comment]
I checked a couple out, these ones all have React Native solutions:

- [Forage](https://www.forage-analytics.com/)
- [Amplitude](https://amplitude.com/)
- [Mixpanel](https://mixpanel.com)
- [Countly](https://count.ly/)
- [MS App Center](https://docs.microsoft.com/en-us/appcenter/analytics/event-metrics#limits) (Link to limits docs)
- [Google Firebase](https://firebase.google.com/pricing?authuser=0&hl=en)

**Comment by Harjot1Singh** [comment]
We're now on PostHog!
