### ISSUE TITLE
Mockup Hukamanama View

### ISSUE THREAD

**Issue by saihaj** [shabados/mobile#78]
Some things to think about when making this:
How they user can access this: Will this be a home screen option?  Something in navigation drawer? 
Options to show in settings menu? 

Related to #74

**Comment by bhajneet** [comment]
Nothing to mock here... 

Dynamic Hukamnamas will show up in bookmarks, they can be subscribed to in a separate area (resolution of which can be made as a new issue, but we're not there anyways, no need yet)

No need for separate stylings
