### ISSUE TITLE
Mockup mobile corrections

### ISSUE THREAD

**Issue by saihaj** [shabados/mobile#81]
Questions to ask yourself when designing:
* User long presses a line and then a pop over comes on?
* A button in reader mode #76 or Shabad view? 
* An option in shake to send feedback as suggested in #67 check this [screenshot](https://user-images.githubusercontent.com/44710980/80322302-c88c7780-87e9-11ea-8838-cf9e54f4af07.jpg)

Related to #74

**Comment by bhajneet** [comment]
Nothing to mock here
