### ISSUE TITLE
Ability to choose app icon

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/mobile#85]
**Describe the solution you'd like**

In settings, user should have an option to choose form multiple app icons.

**Additional context**
Similar to GitHub’s mobile app
![image](https://user-images.githubusercontent.com/44710980/82923380-7baed480-9f40-11ea-8a98-4a99bf476894.jpeg)
![image](https://user-images.githubusercontent.com/44710980/82923396-7f425b80-9f40-11ea-9565-02548d40a03f.png)

**Comment by bhajneet** [comment]
This kind of customization adds little but harms our branding, so I'm closing it as out of scope. If you feel this kind of addition is important to many users we can start a consensus discussion.
