### ISSUE TITLE
Need to change install scripts

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/mobile#87]
**Describe the bug**
In our workflow we don't need to install the pods and that is causing the CI jobs to fail. SO we need to change the install script to that post install doesn't run. 
**To Reproduce**
Check Actions on GitHub

**Expected behavior**
Should get green checkmarks : ) 

**Screenshots**
![image](https://user-images.githubusercontent.com/44710980/84582444-b1154800-adb1-11ea-8ec4-c7ec515e10c7.png)

**Comment by Harjot1Singh** [comment]
Unless in mistaken, it’s only on your branch where you’re not using the `pod-install` package

**Comment by saihaj** [comment]
I forgot that my branches are way behind 😅
