### ISSUE TITLE
Splash screen 

### ISSUE THREAD

**Issue by saihaj** [ShabadOS/mobile#89]
**Describe the solution you'd like**
A cool looking splash screen similar to desktop. Maybe even a dynamic screen based on what season (similar to how mobile games do)

**Additional context**
Can use https://github.com/zoontek/react-native-bootsplash to create these.

**Comment by bhajneet** [comment]
There absolutely cannot be a delay in opening Shabad OS, it should not take as long as opening a game. This would be a band aid, not a solution.
