### ISSUE TITLE
Base shabad view

### ISSUE THREAD

**Issue by saihaj** [shabados/mobile#94]
Render lines in a Shabad. @bhajneet to share mocks.

No support for angs at this point.

### Acceptance Criteria
- Gurbani
- English translation, any for now
- Main view when app opened, blank or with first shabad displayed 
- Floating search bar and bookmarks icon at bottom connected to #95 and #22 screens
- Bonus: Virtualisation with flatrlist or whatnot

**Comment by Harjot1Singh** [comment]
Currently what @saihaj is working on, after discussion of the new designs
