### ISSUE TITLE
Add basic search screen

### ISSUE THREAD

**Issue by saihaj** [shabados/mobile#95]
Add rudimentary search screen.

### Search bar
- Bookmarks button on right. Don't worry about changing this
- Cross when typing input
- Gurmukhi font? @bhajneet unicode entry, or gurmukhi ascii for search? We can implement switching too, but in different issue
- Working back button

### Results list
- Clicking on list item fires some callback
- List items have information components as per mocks (create a component for result item)
- Bonus: Virtualisation with flatlists or whatnot

Please share iOS + Android renders in your PR.

@bhajneet please share relevant mocks.

**Comment by Harjot1Singh** [comment]
Pursuing new design. Updated to reflect this. @bhajneet please share mocks here.

**Comment by bhajneet** [comment]
![image](https://user-images.githubusercontent.com/14130567/103180155-208bea00-4861-11eb-852f-80f584b75946.png)

**Comment by bhajneet** [comment]
Basic doesn't require search history in pane 1, bookmark icon in pane 1

**Comment by saihaj** [comment]
Should I keep this to unicode or do you want me to use ASCII `OpenGurbaniAkhar-Black`? Pinging @Harjot1Singh @bhajneet

**Comment by bhajneet** [comment]
Unicode

**Comment by bhajneet** [comment]
Note: the font should be native to the platform if possible (so you shouldn't need to define any fonts). So "Gurmukhi MT" for iOS, "Noto Sans Gurmukhi" for Android, "Raavi" for Windows (when there is server support from mobile to open a web browser on desktop).

**Comment by saihaj** [comment]
> Cross when typing input

For iOS this is a default behavior for text inputs but for android it is not. So should I add this cross to clear input for android platform or no?

**Comment by bhajneet** [comment]
Yes, add it to Android. Will look up styling later.
