### ISSUE TITLE
Add ESLint rules for stylesheets

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/mobile#97]
**Is your feature request related to a problem? Please describe.**
It would be nice if our CSS had a linter / formatting so it looks uniform. Similar to ESLint for javascript.

**Describe the solution you'd like**
I'd like to see Prettier being used more heavily across multiple file types and then running ESLint/TSLint for whatever is missing in javascript files.

**Comment by saihaj** [comment]
This is related to https://github.com/ShabadOS/desktop/issues/546 but for RN I don't think there is a need for this here because RN has [Stylesheets](https://reactnative.dev/docs/stylesheet#docsNav) and that is JSON like and ESLint is able to format this.

**Comment by bhajneet** [comment]
I can't really think of any other files besides JS/CSS. So if there is nothing else that can benefit from standardized formatting, we can close this issue.

**Comment by bhajneet** [comment]
Also ESLint can make the stylesheet alphabetical and enforce lowercase/uppercase hex codes and such?

**Comment by saihaj** [comment]
> Also ESLint can make the stylesheet css props alphabetical and enforce lowercase/uppercase hex codes and such?

I know that it does enforce camelCase for names but don't think it can force alphabetic ordering

**Comment by saihaj** [comment]
`eslint-plugin-react-native` can require StyleSheet keys to be sorted https://github.com/intellicode/eslint-plugin-react-native/blob/HEAD/docs/rules/sort-styles.md

**Comment by bhajneet** [comment]
Should this issue be closed if it's not resolved ?

**Comment by saihaj** [comment]
My bad because I did that because
> So if there is nothing else that can benefit from standardized formatting, we can close this issue.

But now I think about it we should rename this to say "Add ESLint rules for stylesheets" so that we add those specific rules can be added either to current ESLint config or maybe when we have custom **@ShabadOS/actions** config

**Comment by Harjot1Singh** [comment]
Should this be in Mobile? Are we looking for JS stylesheet linting?

**Comment by saihaj** [comment]
> Should this be in Mobile?
> 
Yes, since the rule mentioned is react-native specific.
> Are we looking for JS stylesheet linting?
> 

Yes

Thanks and Regards 
Saihajpreet Singh

**Comment by Harjot1Singh** [comment]
https://dev.to/chgldev/getting-prettier-eslint-and-vscode-to-work-together-3678

This is more inline with what we're looking for, but we still need to figure out prettier support for the rest of the files

**Comment by Harjot1Singh** [comment]
Closed by #102 and closed by #109.

**Comment by bhajneet** [comment]
I don't think this should be closed until Stylesheet is sorted properly. For instance:

```
const styles = StyleSheet.create( {
  welcomeContent: {
    marginTop: '5%',
    alignItems: 'center',
  },
  welcomeLogo: {
    width: '30%',
    height: 100,
    marginTop: '5%',
    marginBottom: '5%',
  },
  brand: {
    fontSize: 35,
    fontWeight: 'bold',
  },
} )
```

Should become:

```
const styles = StyleSheet.create( {
  brand: {
    fontSize: 35,
    fontWeight: 'bold',
  },
  welcomeContent: {
    marginTop: '5%',
    alignItems: 'center',
  },
  welcomeLogo: {
    width: '30%',
    height: 100,
    marginTop: '5%',
    marginBottom: '5%',
  },
} )
```

**Comment by Harjot1Singh** [comment]
Descending order?

**Comment by Harjot1Singh** [comment]
https://github.com/Intellicode/eslint-plugin-react-native/blob/master/docs/rules/sort-styles.md enable for only style names and not properties
